export const workList = [
  {
    id: "work1",
    img: "work1.jpeg",
    url: "https://react-slotgame.vercel.app/",
    title: "スロットゲーム",
    skill: "React/TailwindCSS",
    desc: "講義で学んだスロットマシンをReactで書き換えました。オリジナルで機能を追加して本格的なスロットゲームに仕立てました。",
    gitHubUrl: "https://github.com/i-ji/dot-react-slot",
  },
  {
    id: "work2",
    img: "work2.jpeg",
    url: "https://next-sns-server-actions.vercel.app/",
    title: "Twitter風SNS",
    skill: "Next.js/TailwindCSS/supabase",
    desc: "フロンドエンド部分をNext.js,バックエンド部分をsupabaseを使ったフルスタックアプリケーションです。server actionsなどの最新の技術も使用しました。",
    gitHubUrl: "https://github.com/i-ji/next-sns-server-actions",
  },
  {
    id: "work3",
    img: "work3.jpeg",
    url: "https://nextjs-pokequiz.vercel.app/",
    title: "ポケモン中国語クイズ",
    skill: "Next.js/TypeScript/TailwindCSS",
    desc: "pokeAPIを使用して、中国語のオリジナルクイズを作成しました。",
    gitHubUrl: "https://github.com/i-ji/nextjs-pokequiz",
  },
  {
    id: "work4",
    img: "work4.jpeg",
    url: "https://nextjs-pokezukan.vercel.app/",
    title: "ポケモン図鑑",
    skill: "Next.js/TypeScript/TailwindCSS",
    desc: "pokeAPIを使用して、ポケモン図鑑を作成しました。",
    gitHubUrl: "https://github.com/i-ji/nextjs-pokezukan",
  },
  {
    id: "work5",
    img: "work5.jpg",
    url: "https://redux-pacing.vercel.app/",
    title: "ペース計算アプリ",
    skill: "React/TypeScript/TailwindCSS",
    desc: "距離やタイムからペースの計算をしてくれるアプリです。",
    gitHubUrl: "https://github.com/i-ji/redux-pacing",
  },
  {
    id: "work6",
    img: "work6.jpg",
    url: "https://exercise-intensity.vercel.app/",
    title: "運動強度測定アプリ",
    skill: "React/TypeScript/TailwindCSS",
    desc: "年齢や安静時心拍数からより正確な運動強度を測定するアプリです。",
    gitHubUrl: "https://github.com/i-ji/redux-exerciseIntensity",
  },
  {
    id: "work7",
    img: "work7.jpg",
    url: "https://next-tricolor-list.vercel.app/",
    title: "３色リスト",
    skill: "Next.js/TypeScript/TailwindCSS",
    desc: "買い物リスト・TODOリスト・持ち物リストを一つにまとめた管理タスクアプリです。",
    gitHubUrl: "https://github.com/i-ji/next-tricolor-list",
  },
];
